services:

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user:8000
      - MATCH_SERVICE_URL=http://match_service:8000
      - EVENT_SERVICE_URL=http://event_service:8080
      - JWT_SECRET=hYsEyN01CaMrYsaidAhmad02BysicleNuRaDi03pRiorapoiuytrewwkcdkghdmv
    depends_on:
      - user
      - match_service
      - event_service

  user:
    build:
      context: ./user
    container_name: user
    environment:
      - DB_HOST=db_user
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=user_service
      - JWT_SECRET=hYsEyN01CaMrYsaidAhmad02BysicleNuRaDi03pRiorapoiuytrewwkcdkghdmv
    depends_on:
      - db_user

  event_service:
    build:
      context: ./event_service
    container_name: event_service
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=db_event
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=7213
      - DB_NAME=event_service
      - MATCH_SERVICE_URL=http://match_service:8000
      - KAFKA_BROKER=kafka:9093
      - REDIS_ADDR=redis:6379
    depends_on:
      - db_event
      - match_service
      - kafka
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  match_service:
    build:
      context: ./match_service
    container_name: match_service
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=db_match
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=match_service
      - KAFKA_BROKER=kafka:9093
      - REDIS_ADDR=redis:6379
    depends_on:
      - db_match
      - kafka
      - redis

  db_user:
    image: postgres:17
    container_name: db_user
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_service
    ports:
      - "5479:5432"
    volumes:
      - pg_user:/var/lib/postgresql/data

  db_event:
    image: postgres:17
    container_name: db_event
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7213
      - POSTGRES_DB=event_service
    ports:
      - "5499:5432"
    volumes:
      - pg_event:/var/lib/postgresql/data

  db_match:
    image: postgres:17
    container_name: db_match
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=match_service
    ports:
      - "5489:5432"
    volumes:
      - pg_match:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka

volumes:
  pg_user:
  pg_event:
  pg_match: