services:
  event_service:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db_event
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=7213
      - DB_NAME=event_service
    env_file:
      - ./event_service/.env
    depends_on:
      - db_event
      
match_service:
  build:
    context: ./match_service
    dockerfile: Dockerfile
  container_name: match_service
  ports:
    - "8001:8000"         
  environment:
    - DB_HOST=db_match
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=match_service
    - KAFKA_BROKER=kafka:9093
  env_file:
    - ./match_service/.env
  depends_on:
    - db_match
    - kafka
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7213
      - POSTGRES_DB=event_service
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

db_match:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=match_service
    ports:
      - "5434:5432"
    volumes:
      - pg_match:/var/lib/postgresql/data

  # Kafka — брокер сообщений
kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"     # Порт для внешних подключений (Go приложения)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Kafka UI — веб-интерфейс для просмотра топиков
kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
volumes:
  pg_event:
  pg_match: